name: Built, tested and 100% covered

on: [push, pull_request]

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - uses: actions/checkout@v2.3.4
      with:
        ref: main
        path: main
    - uses: actions/checkout@v2.3.4
      with:
        path: pr
    - run: npm install
      working-directory: ./main
    - run: npm test
      working-directory: ./main
    - run: npm install
      working-directory: ./pr
    - run: npm test
      working-directory: ./pr
    - uses: vebr/jest-lcov-reporter@v0.2.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./pr/coverage/lcov.info
        lcov-base: ./main/coverage/lcov.info
    - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
      with:
        min_coverage: 100
        path: "./pr/coverage/lcov.info"